%strings
process_path_pref="/home/robu/dwSun/数字化病理/sample_data/process";
name="HCC-05-N1-NEG_gaussian_ada";
edge_type_list='ada';
test_sample_all_file='test_samples_275.mat';
top_k_name_list='test_samples_20';
%float
rbm_ratio_list=0.1;
beta_list=0.5;
%int
nei_type=4;
divn_list=20;
epoch_list=5;
h=256;
w=256;